version: '3.8'

name: lp_mdsu
services:
  lp_mdsu:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    networks:
      - traefik_net
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes: []
    command: >
      sh -c 'if [ "$NODE_ENV" = "production" ]; then npm run preview -- --port 4173; else npm run dev -- --port 5173; fi'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lp_mdsu.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.lp_mdsu.entrypoints=websecure"
      - "traefik.http.routers.lp_mdsu.tls.certresolver=resolver"
      - "traefik.http.services.lp_mdsu.loadbalancer.server.port=4173"

networks:
  traefik_net:
    external: true
